apis/s3/src/main/java/org/jclouds/s3/filters/Aws4SignerBase.java

Ensure the canonicalRequest is logged properly

---

core/src/main/java/org/jclouds/util/Predicates2.java

Fix always-true date comparison

---

providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/domain/Region.java

Related news: [Microsoft opens first datacenters in Africa with general availability of Microsoft Azure](https://azure.microsoft.com/en-us/blog/microsoft-opens-first-datacenters-in-africa-with-general-availability-of-microsoft-azure/?ranMID=24542&ranEAID=TnL5HPStwNw&ranSiteID=TnL5HPStwNw-tAHfeVMsJxlTB0HTf5u5hg&epi=TnL5HPStwNw-tAHfeVMsJxlTB0HTf5u5hg&irgwc=1&OCID=AID681541_aff_7593_1243925&tduid=(ir__lzno3kzeixnvs0cbi2ggngmlx22xmws0ilole2sf00)(7593)(1243925)(TnL5HPStwNw-tAHfeVMsJxlTB0HTf5u5hg)()&irclickid=_lzno3kzeixnvs0cbi2ggngmlx22xmws0ilole2sf00)

Adds new Generally Available azure locations for South Africa

---

providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/AzureComputeApi.java
providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/compute/extensions/AzureComputeSecurityGroupExtension.java
providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/features/NetworkSecurityGroupApi.java
providers/azurecompute-arm/src/test/java/org/jclouds/azurecompute/arm/features/NetworkSecurityGroupApiLiveTest.java
providers/azurecompute-arm/src/test/java/org/jclouds/azurecompute/arm/features/NetworkSecurityGroupApiMockTest.java
providers/azurecompute-arm/src/test/resources/networksecuritygrouplistall.json

https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networksecuritygroups/listall
Will improve performance and number of API calls in `AzureComputeSecurityGroupExtension.securityGroupsInLocations`

Implements listAll method in NetworkSecurityGroupApi

---

providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/AzureComputeApi.java
providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/features/LoadBalancerApi.java
providers/azurecompute-arm/src/test/java/org/jclouds/azurecompute/arm/features/LoadBalancerApiLiveTest.java
providers/azurecompute-arm/src/test/java/org/jclouds/azurecompute/arm/features/LoadBalancerApiMockTest.java
providers/azurecompute-arm/src/test/resources/loadbalancerlistall.json

Another performance and rate limit improvement.
In this case there's no abstraction implemented for loadbalancers but jclouds users can access the exposed APIs to get the improvement.

Implements listAll method for LoadBalancersAPI

---

providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/AzureComputeApi.java
providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/features/VirtualNetworkApi.java
providers/azurecompute-arm/src/test/java/org/jclouds/azurecompute/arm/features/VirtualNetworkApiLiveTest.java
providers/azurecompute-arm/src/test/java/org/jclouds/azurecompute/arm/features/VirtualNetworkApiMockTest.java
providers/azurecompute-arm/src/test/resources/listvirtualnetworksall.json

This should be the last of these improvements.
Again jclouds doesn't use the method

Implements listAll operation for VirtualNetworkAPI

---

providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/domain/Region.java

Also seems that new Abu Dhabi will be released soon but actually it does not work.

Add new Azure Dubai region

---

providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/compute/AzureComputeServiceAdapter.java
providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/compute/options/AzureTemplateOptions.java

Fix https://issues.apache.org/jira/browse/JCLOUDS-1514

Add OS disk type in template options

---

README.md

Also opening this to test pull request CI triggers

Update README copyright dates

---

drivers/apachehc/src/main/java/org/jclouds/http/apachehc/ApacheHCHttpCommandExecutorService.java

proposal fix for issue reported in
https://issues.apache.org/jira/projects/JCLOUDS/issues/JCLOUDS-1505

Fix null content-length header on HEAD requests

---

apis/sts/src/main/java/org/jclouds/aws/domain/Region.java
providers/aws-ec2/src/main/java/org/jclouds/aws/ec2/AWSEC2ProviderMetadata.java
providers/aws-ec2/src/test/java/org/jclouds/aws/ec2/compute/AWSEC2TemplateBuilderLiveTest.java
providers/aws-s3/src/main/java/org/jclouds/aws/s3/AWSS3ProviderMetadata.java
providers/aws-s3/src/test/java/org/jclouds/aws/s3/blobstore/integration/AWSS3ServiceIntegrationLiveTest.java

This change request is to add the Middle East (Bahrain) region to the AWS EC2 and S3 providers list.
I was able to compile it on my forked repo but as this is my first pull request, I want to make sure I missed nothing.

JCLOUDS-1541: Add Middle East (Bahrain) region to the AWS EC2 and S3 providers list

---

.travis.yml

This PR enables doc and src profiles on travis

Enable docs in travis build

---

blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java

This avoids an unneeded call to `ByteStreams2.toByteArrayAndClose` in
`getBlob` for range requests and elides a large memory allocation.

JCLOUDS-1367: Do not open open InputStream in copyBlob

---

project/pom.xml

Release notes:
https://github.com/google/guice/wiki/Guice423

JCLOUDS-1498: Upgrade to Guice 4.2.3

---

apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java
blobstore/src/main/java/org/jclouds/blobstore/LocalStorageStrategy.java
blobstore/src/main/java/org/jclouds/blobstore/TransientStorageStrategy.java
blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java

This addresses a race condition with filesystem users.

Allow setting BlobAccess in LocalBlobStore.putBlob

---

apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java

Paths created by `Files.createParentDirs` lack extended attributes and
thus Content-Type for directories.

Force application/x-directory for directories

---

project/pom.xml

This does strange things with the java compiler which makes it
incompatible with more modern Java versions.

Remove error-prone

---

apis/s3/src/main/java/org/jclouds/s3/S3Client.java

First putblob should be signed with specific region rather than with default region during createcontainer API 
https://issues.apache.org/jira/browse/JCLOUDS-1516

J clouds 1516

---

project/pom.xml

This upgrades asm which improves compatibility with modern Java.
Release notes:
https://github.com/easymock/easymock/releases

Upgrade to EasyMock 4.3

---

project/pom.xml

This addresses a bad class file issues seen when using an explicit
JAXB dependency.  Release notes:
https://github.com/mojohaus/animal-sniffer/releases

Upgrade animal sniffer to 1.20

---

core/src/test/java/org/jclouds/osgi/MetadataBundleListenerTest.java

Java 9 returns `jdk.internal.loader.ClassLoaders$AppClassLoader` instead
of `URLClassLoader` so we cannot create an isolated `ClassLoader`.

Remove tests which rely on an isolated ClassLoader

---

providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/functions/URIParser.java

Fix https://issues.apache.org/jira/browse/JCLOUDS-1569

Fix location header case sensitive

---

apis/atmos/src/main/java/org/jclouds/atmos/filters/SignRequest.java
apis/s3/src/main/java/org/jclouds/s3/filters/Aws4SignerForAuthorizationHeader.java
apis/s3/src/main/java/org/jclouds/s3/filters/Aws4SignerForChunkedUpload.java
apis/sts/src/main/java/org/jclouds/aws/filters/FormSignerV4.java

Prefer case-insenstive header comparisons

---

apis/s3/src/main/java/org/jclouds/s3/domain/ObjectMetadata.java

Add new `GLACIER_IR `enum to ObjectMetadata
https://issues.apache.org/jira/browse/JCLOUDS-1599

JCLOUDS-1599 - Add support for GLACIER_IR storage class

---

drivers/bouncycastle/pom.xml

Release notes:
https://www.bouncycastle.org/releasenotes.html#r1rv71

JCLOUDS-1609: Upgrade to BouncyCastle 1.71

---

project/pom.xml

see https://maven.apache.org/guides/mini/guide-reproducible-builds.html

activate Reproducible Builds

---

project/pom.xml

Release notes:
https://github.com/google/guice/wiki/Guice510

Upgrade to Guice 5.1.0

---

apis/byon/pom.xml
apis/byon/src/main/java/org/jclouds/byon/domain/YamlNode.java
apis/byon/src/main/java/org/jclouds/byon/functions/NodesFromYamlStream.java

This has some API changes.  Closes #169.

Upgrade to snakeyaml 2.0

---

project/pom.xml

Release notes:
https://github.com/apache/maven-surefire/releases/tag/surefire-3.0.0
https://github.com/apache/maven-surefire/releases/tag/surefire-3.1.0

Upgrade to surefire 3.1.0

---

project/pom.xml

Remove unneeded -XX:MaxPermSize=256m

---

apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java

All folders are returned as type Blob

FilesystemStorageStrategyImpl.getBlob() return folder as type Blob

---

core/src/main/java/org/jclouds/io/payloads/MultipartForm.java
core/src/test/java/org/jclouds/io/payloads/MultipartFormTest.java

https://issues.apache.org/jira/browse/JCLOUDS-1632

JCLOUDS-1632: GCP BlobStore fails to put a blob if blob name contains non ASCII characters

---

.github/workflows/ci.yaml

v4 is the latest version of setup-java

setup-java v3 -> v4

---

providers/google-compute-engine/src/main/java/org/jclouds/googlecomputeengine/domain/Warning.java

org.jclouds.googlecomputeengine.domain.Warning: Add nullable annotation to code and data attributes

Tentative fix for https://issues.apache.org/jira/browse/JCLOUDS-1643
