providers/azureblob/src/main/java/org/jclouds/azureblob/config/AzureBlobHttpApiModule.java
providers/azureblob/src/test/java/org/jclouds/azureblob/config/AzureBlobHttpApiModuleTest.java

Need to remove "sp" and "se" tokens from the SAS check, since there is a possible SAS format without those two tokens;
Added a unit test case.

JCLOUDS-1428 - Support for SAS token based Authentication for Azure Blob Storage - Follow Up

---

apis/openstack-keystone/pom.xml
project/pom.xml

Some maven plugins are not properly addressed.

JCLOUDS-1495: maven plugins are not correctly referred to

---

core/src/main/java/org/jclouds/Constants.java
core/src/main/java/org/jclouds/apis/internal/BaseApiMetadata.java
core/src/main/java/org/jclouds/http/internal/JavaUrlHttpCommandExecutorService.java
core/src/main/java/org/jclouds/io/ByteStreams2.java
core/src/test/java/org/jclouds/http/internal/TrackingJavaUrlHttpCommandExecutorService.java
providers/dynect/src/main/java/org/jclouds/dynect/v3/config/DynECTHttpApiModule.java
providers/profitbricks/src/main/java/org/jclouds/profitbricks/http/ResponseStatusFromPayloadHttpCommandExecutorService.java

This change improves the performance of writing to sockets with the
default Java URL connection HTTP client, by enlarging the buffer used
for socket writes from an implicit hard-coded 4KB / 8KB buffer to a
configurable 32KB buffer.
The buffer size is now controlled by the following property with the
following default value:
jclouds.output-socket-buffer-size: 32768
The implementation is based on a variant of ByteStreams.copy (written as
ByteStreams2.copy) which accepts the buffer size as an argument, unlike
the original Guava code that uses a hard-coded size.
The change was done directly within the loop that copies the input
stream to the output stream, and not by wrapping a BufferedOutputStream
around the existing output stream, in order to avoid copying the payload
twice.
On some …

JCLOUDS-847: Poor upload performance for putBlob

---

project/pom.xml

As far as I can see, the ossrh repository (https://oss.sonatype.org/content/repositories/snapshots)
is not needed.
It slows down compilation considerably.
Lets remove the maven repository from the pom

JCLOUDS-1499: Disable sonatype snapshot repository for plugins

---

apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/LimitApiTest.java
apis/cloudstack/src/test/java/org/jclouds/cloudstack/features/SecurityGroupApiTest.java
apis/ec2/src/test/java/org/jclouds/ec2/xml/RunInstancesResponseHandlerTest.java
apis/openstack-nova/src/main/java/org/jclouds/openstack/nova/v2_0/domain/regionscoped/AvailabilityZone.java
apis/openstack-nova/src/main/java/org/jclouds/openstack/nova/v2_0/domain/regionscoped/AvailabilityZoneDetails.java
apis/openstack-nova/src/main/java/org/jclouds/openstack/nova/v2_0/domain/regionscoped/Hypervisor.java
apis/openstack-nova/src/main/java/org/jclouds/openstack/nova/v2_0/domain/zonescoped/AvailabilityZone.java
apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/TempAuthMockTest.java
project/pom.xml
providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/domain/DeploymentTemplate.java
providers/rackspace-cloudblockstorage-uk/src/test/java/org/jclouds/rackspace/cloudblockstorage/uk/CloudBlockStorageUKProviderMetadataExpectTest.java
providers/rackspace-cloudblockstorage-us/src/test/java/org/jclouds/rackspace/cloudblockstorage/us/CloudBlockStorageUSProviderMetadataExpectTest.java
providers/rackspace-clouddatabases-uk/src/test/java/org/jclouds/rackspace/clouddatabases/uk/CloudDatabasesUKProviderMetadataExpectTest.java
providers/rackspace-clouddatabases-us/src/test/java/org/jclouds/rackspace/clouddatabases/us/CloudDatabasesUSProviderMetadataExpectTest.java
providers/rackspace-cloudservers-uk/src/test/java/org/jclouds/rackspace/cloudservers/uk/CloudServersUKProviderMetadataExpectTest.java
providers/rackspace-cloudservers-us/src/test/java/org/jclouds/rackspace/cloudservers/us/CloudServersUSProviderMetadataExpectTest.java
resources/checkstyle.xml
resources/pom.xml

This is the jclouds part of fixing checkstyle. jclouds-labs has a couple of violations as well

JCLOUDS-1497: Fix checkstyle-suppressions for jcloud-labs

---

providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/compute/config/AzurePredicatesModule.java
providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/compute/extensions/AzureComputeSecurityGroupExtension.java
providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/domain/NetworkSecurityRuleProperties.java
providers/azurecompute-arm/src/test/java/org/jclouds/azurecompute/arm/features/NetworkSecurityGroupApiMockTest.java
providers/azurecompute-arm/src/test/java/org/jclouds/azurecompute/arm/features/NetworkSecurityRuleApiMockTest.java
providers/azurecompute-arm/src/test/resources/networksecurityrulecreate.json

* We were checking the provisioningState security group resource. When updating rules concurrently this check returns OK (the security group is ok) but the actual rules are still being updated (created/deleted) causing random problems.
* PR implements provisioningState in `NetworkSecurityRuleProperties` to do this check properly (https://docs.microsoft.com/en-us/rest/api/virtualnetwork/securityrules/get#securityrule)

Checks provisioning state in Rule resource instead of Group

---

providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/config/AzureBlobStoreContextModule.java
providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/functions/BlobPropertiesToBlobMetadata.java
providers/azureblob/src/main/java/org/jclouds/azureblob/config/InsufficientAccessRightsException.java

Removed the ACL check for the AzureBlobs, authorised with SAS Auth String. 
Implemented all change requests from the previous PR #23.

JCLOUDS-1428 - Support for SAS token based Authentication for Azure Blob Storage

---

providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/functions/BlobPropertiesToBlobMetadata.java

Fix a regression introduced in https://github.com/apache/jclouds/pull/34
The method implements `Function` and cannot declare an exception to be thrown, so we should only propagate RuntimeExceptions.
It is fine to just catch that since the methods inside the catch block are not meant to throw checked exceptions.
/cc @ak58588

Fix regression in azureblob and properly catch unchecked exceptions

---

core/src/main/java/org/jclouds/json/internal/DeserializationConstructorAndReflectiveTypeAdapterFactory.java
gson/gson-shaded/pom.xml

If we do not have to consider to fix JCLOUDS-1166 in the first place (using of internal gson API) , updating gson is a piece of cake

JCLOUDS-1500: Update gson to 2.8.5

---

core/src/main/java/org/jclouds/http/functions/ParseSax.java

This commit prevents the `convertStreamToStringAndParse` method from
failing XML validation on environments in which the default charset is
not compatible with UTF-8.

JCLOUDS-1510: ParseSax use charset constant for all String creations

---

.travis.yml

ASF Jenkins PR builds are only enabled for PRs made by committers and PMC members. To have PR builds on all contributions, we requested that TracisCI was enabled in the repos.
This PR adds a basic config file so Travis builds are triggered on PRs.

Add TravisCI file for pull requests

---

drivers/apachehc/src/main/java/org/jclouds/http/apachehc/config/ApacheHCHttpCommandExecutorServiceModule.java

Because the Java type BasicHttpParams wasn't matching the one returned
by provider "newBasicHttpParams" (which is returning a HttpParams type), it was configuring the Apache HTTP client with default settings (including connection and socket timeout), ignoring the ones of JClouds which were must safer in this regard (JCloudsones are currently 60sec for both, while Apache HC ones are -1, so infinite). It also prevented to override those default/infinite timeout settings with JClouds ones.

Fix infinite socket timeout when using ApacheHCHttpCommandExecutorServiceModule

---

drivers/bouncycastle/pom.xml

This version fixes the CVEs, yet also works with Oracle JDK 1.7.
@nacx

Downgrade BouncyCastle to 1.60, which works with Oracle JDK 1.7

---

core/pom.xml

use constraint violation with OSGi.
https://issues.apache.org/jira/browse/JCLOUDS-1529

JCLOUDS-1529: Do not export org.jclouds.json.gson.internal because it causes a

---

drivers/apachehc/src/main/java/org/jclouds/http/apachehc/ApacheHCHttpCommandExecutorService.java

JClouds is apparently exclusively using the Payload object from the HTTP
response to fill in the size of the BlobMetadata (when calling
blobStore.blobMetadata(...) ) - adapt this driver accordingly otherwise
we systematically get null size BlobMetadata out of it.

Fix BlobMetadata null size when using ApacheHCHttp module

---

pom.xml
project/pom.xml

This fixes javadoc generation with JDK >= 8 so that someone with write-permission to the jclouds.apache.org site can fix apache/jclouds-site#12
Corresponding JIRA-Issue: [JCLOUDS-1544](https://issues.apache.org/jira/browse/JCLOUDS-1544)
Note: This also applies to the 2.2.x branch, shall I create another PR for that?
Cheers
-Fritz

Fix javadoc generation on JDK >= 8

---

project/pom.xml

This PR fixes the jenkins-specific case introduced by my PR #67 where maven is run by jdk8 and then the toolchain-plugin is used to downgrade the toolchain to jdk1.7.
This was tested successfully in 3 scenarios:
1. Maven executed by JDK7, jenkins profile deactivated
1. Maven executed by JDK8, jenkins profile deactivated
3. Maven executed by JDK8, jenkins profile activated and jdk.version set to 1.7
It will **not** work if maven is executed by JDK>=8 **and** jenkins profile is activated **and** jdk.version is set to anything > 1.7 (For that to work, you have to revert this patch)
In my humble opinion, jenkins-specific setup (or any CI for that matter) does not belong into a project's pom.xml. Instead, this should be solved entirely on jenkins itself. (e.g. by setting up a freestyle job …

Fix toolchain setup on jenkins

---

providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/domain/DomainResourceReferences.java
providers/google-cloud-storage/src/test/java/org/jclouds/googlecloudstorage/features/BucketApiLiveTest.java
providers/google-cloud-storage/src/test/java/org/jclouds/googlecloudstorage/features/ObjectApiLiveTest.java

Also change portable abstraction mapping for `Tier.ARCHIVE`.

JCLOUDS-1546: Support GCS Archive storage class

---

blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobIntegrationTest.java
core/src/main/java/org/jclouds/http/internal/PayloadEnclosingImpl.java
core/src/main/java/org/jclouds/io/PayloadEnclosing.java
providers/b2/src/test/java/org/jclouds/b2/blobstore/integration/B2BlobIntegrationLiveTest.java
providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/binders/MultipartUploadBinder.java
providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/blobstore/GoogleCloudStorageBlobStore.java

Previously this provider worked around a RestAnnotationProcessor quirk
by using multi-part uploads for InputStream payloads.  Instead work
around the quirk another way which allows a single-part upload.  This
allows inclusion of the Content-MD5 header during object creation.
Backfill tests with both ByteSource and InputStream inputs.

JCLOUDS-912: JCLOUDS-1547: GCS InputStream single-part upload

---

allblobstore/pom.xml
apis/chef/src/test/java/org/jclouds/chef/features/OrganizationApiExpectTest.java
apis/openstack-nova/src/main/java/org/jclouds/openstack/nova/v2_0/compute/functions/ImageToOperatingSystem.java
apis/openstack-nova/src/main/java/org/jclouds/openstack/nova/v2_0/compute/strategy/ApplyNovaTemplateOptionsCreateNodesWithGroupEncodedIntoNameThenAddToSet.java
blobstore/src/main/java/org/jclouds/blobstore/strategy/internal/DeleteAllKeysInList.java
compute/src/main/java/org/jclouds/compute/extensions/internal/DelegatingImageExtension.java
compute/src/main/java/org/jclouds/compute/stub/config/StubComputeServiceDependenciesModule.java
core/src/main/java/org/jclouds/concurrent/config/ExecutorServiceModule.java
core/src/main/java/org/jclouds/predicates/InetSocketAddressConnect.java
core/src/main/java/org/jclouds/proxy/ProxyForURI.java
core/src/main/java/org/jclouds/rest/internal/InvokeHttpMethod.java
core/src/test/java/org/jclouds/rest/internal/BaseRestApiExpectTest.java
core/src/test/java/org/jclouds/rest/internal/BaseRestApiTest.java
core/src/test/java/org/jclouds/rest/internal/InvokeHttpMethodTest.java
drivers/jsch/src/main/java/org/jclouds/ssh/jsch/JschSshClient.java
drivers/jsch/src/main/java/org/jclouds/ssh/jsch/SessionConnection.java
drivers/sshj/src/main/java/org/jclouds/sshj/SSHClientConnection.java
drivers/sshj/src/main/java/org/jclouds/sshj/SshjSshClient.java
project/pom.xml
providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/compute/config/AzureNameValidator.java

This allows compatibility with Guava 29.  Also unwind some older
workarounds.

JCLOUDS-1333: JCLOUDS-1334: JCLOUDS-1470: Require Java 8 and Guava 22

---

apis/s3/src/main/java/org/jclouds/s3/domain/ObjectMetadata.java

To solve the following stacktrace:
`java.lang.IllegalArgumentException: No enum constant org.jclouds.s3.domain.ObjectMetadata.StorageClass.INTELLIGENT_TIERING
at java.lang.Enum.valueOf(Enum.java:238)
at org.jclouds.s3.domain.ObjectMetadata$StorageClass.valueOf(ObjectMetadata.java:36)
at org.jclouds.s3.functions.ParseObjectMetadataFromHeaders.apply(ParseObjectMetadataFromHeaders.java:81)
at org.jclouds.s3.functions.ParseObjectFromHeadersAndHttpContent.apply(ParseObjectFromHeadersAndHttpContent.java:48)
at org.jclouds.s3.functions.ParseObjectFromHeadersAndHttpContent.apply(ParseObjectFromHeadersAndHttpContent.java:34)
at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
at …

JCLOUDS-1473 add INTELLIGENT_TIERING enum

---

core/src/main/java/org/jclouds/reflect/Reflection2.java

With Java 11, an illegal reflective access is output for the google cloud storage blobstore.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jclouds.reflect.Reflection2$1 (file:/.../jclouds-core.jar) to constructor java.lang.String(char[],int,int,java.lang.Void)
WARNING: Please consider reporting this to the maintainers of org.jclouds.reflect.Reflection2$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Indeed, JClouds calls `setAccessible(true)` on the package protected constructor
`java.lang.String(char[],int,int,java.lang.Void)`.
Investigating the code, it turns out it is looking for constructors annotated …

JCLOUDS-1542 Java 11 warns of illegal reflective access

---

core/src/main/java/org/jclouds/reflect/Reflection2.java

`AccessibleObject.canAccess()` would be much much better,
but this API can only be used from Java 9 onward.
Note: I have not tested this code, I will see if we can test it on Monday.
I have opened the PR to get the review going and see if anything needs to be changed.
Thank you!

JCLOUDS-1542 follow-up: check whether isAccessible() is already set

---

blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java

Previously this allocated a byte array for every call.

Optimize MultiBlobInputStream.read()

---

apis/sts/src/main/java/org/jclouds/aws/util/AWSUtils.java
apis/sts/src/test/java/org/jclouds/aws/util/AWSUtilsTest.java
core/src/main/java/org/jclouds/http/HttpUtils.java

In  case of empty response, AWSUtil returns null, but produces WARN logspam.
https://issues.apache.org/jira/browse/JCLOUDS-1552

JCLOUDS-1552: Do not attempt to parse empty payload

---

core/src/main/java/org/jclouds/http/functions/ParseJson.java
core/src/main/java/org/jclouds/json/Json.java
core/src/main/java/org/jclouds/json/internal/GsonWrapper.java
core/src/test/java/org/jclouds/json/JsonTest.java

My local test suite is failing due to an incorrect exception message tested by ParseSaxTest.testAddDetailsAndPropagateOkWithValidRequestResponseWithSAXParseException (running with Java 1.8)

JCLOUDS-1559: add Charset to Json.fromJson InputStream methods

---

apis/s3/src/main/java/org/jclouds/s3/binders/BindACLToXMLPayload.java
apis/s3/src/main/java/org/jclouds/s3/binders/BindBucketLoggingToXmlPayload.java
apis/s3/src/main/java/org/jclouds/s3/binders/BindIterableAsPayloadToDeleteRequest.java
project/pom.xml

- animal sniffer should be on java18, just like `<jdk.version>`
- Only use XMLBuilder's elem() and text() methods to have similar looking code
- Remove unnecessary call to XMLBuilder's up() because the returned value is never used
- Simplify code
- Deduplicate code
- Make the code more explicit by returning the rootBuilder

Simplify S3 code that uses java-xml-builder

---

apis/chef/pom.xml
apis/docker/pom.xml
apis/openstack-keystone/pom.xml
apis/openstack-neutron/pom.xml
apis/openstack-nova/pom.xml
core/pom.xml
project/bnd.bnd
project/pom.xml
providers/rackspace-cloudservers-uk/pom.xml
providers/rackspace-cloudservers-us/pom.xml

- Increase version of Guava dependency from 22.0 to 27.1-jre.
Note: In an OSGi runtime, Guice version 4.2.3 expects Guava with an exact version of 27.1-jre. For now, higher versions of Guava are not possible.
- Separate version numbers from dependencies and plugins
To understand the scope of the modification work performed in the feature branch, I refer you to the notes listed in the individual commits.
**Due to an approaching release, these optional modifications will be considered in the upcoming development circle.**
https://issues.apache.org/jira/browse/JCLOUDS-1555
~~Following is a description of the purpose of the feature.~~
~~New contributors find it difficult to understand the function and intent of different plugins integrated into JClouds.~~
~~The primary goal is to simplify and …

Initial cleanup of maven set up in the parents' module

---

apis/s3/pom.xml
apis/s3/src/main/java/org/jclouds/s3/binders/BindACLToXMLPayload.java
apis/s3/src/main/java/org/jclouds/s3/binders/BindBucketLoggingToXmlPayload.java
apis/s3/src/main/java/org/jclouds/s3/binders/BindIterableAsPayloadToDeleteRequest.java
apis/s3/src/main/java/org/jclouds/s3/binders/XMLHelper.java
project/pom.xml

XMLBuilder is a very nice fluent API for building XML documents.
However, it is only used by a tiny portion of jclouds: the s3 api. The
use of the XMLBuilder class requires a dependency to
com.jamesmurty.utils:java-xmlbuilder jar and a transitive
dependency to the net.iharder:base64 jar (superseded by
java.util.Base64 in java 8). They are 18kb each approximately and they
not OSGi compatible. They are not huge, but they represent more API
surface and more things to change when trying to use jclouds in an OSGi
context (they need to be replaced by OSGi compatible bundles like
org.apache.servicemix.bundles.java-xmlbuilder).
This commit replaces the use of XMLBuilder by a direct use of the
javax.xml and org.w3c.dom APIs.
I hope retesting will be minimal, and most of this code is covered by …

S3 APIs: Remove the dependency to com.jamesmurty.utils:java-xmlbuilder

---

apis/s3/src/main/java/org/jclouds/s3/domain/CanonicalUser.java
apis/s3/src/main/java/org/jclouds/s3/xml/ListAllMyBucketsHandler.java
apis/s3/src/test/java/org/jclouds/s3/xml/S3ParserTest.java

Currently, jclouds assumes that the ListBuckets response follows a
specific order: the <Owner> tag, followed by the <Buckets> tag. Within
the <Owner> tag, jclouds further assumes that the <ID> must occur before
the <DisplayName> tag. If the XML body does not adhere to this order,
the parser throws a NullPointerException.
DigitalOcean spaces does not adhere to this order and returns the
<DisplayName> tag before the <ID> tag. The patch changes the parser to
not depend on the order of the tags.

Do not assume Owner ID comes first in XML for S3

---

apis/openstack-swift/src/main/java/org/jclouds/openstack/swift/v1/functions/EntriesWithoutMetaPrefix.java
apis/openstack-swift/src/test/java/org/jclouds/openstack/swift/v1/features/ObjectApiMockTest.java

The issue happens if a cloud provider returns lowercase metadata headers, for example: "x-object-meta-apiversion" instead of "X-Object-Meta-ApiVersion"
In that case, BlobStore.blobMetadata(CONTAINER, PATH).getUserMetadata()
incorrectly returns an empty map.
This happens because the code is looking for the exact String "-Meta-" (case-sensitive).
This checkin allows to handle metadata headers of any case, and also adds a unit test for that situation.

JCLOUDS-1580 - Add support for lowercase metadata headers

---

blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java

This fixes a memory regression from
8de7b696e13f7131b3ea4a77b10f5cfd139dd712 where the transient `BlobStore`
changed from a `ByteSource` to a `byte[]`.

Re-optimize LocalBlobStore.getBlob with ranges

---

providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/domain/Bucket.java

This field is not required:
https://cloud.google.com/storage/docs/cross-origin#cors-elements

JCLOUDS-1581: Make CORS maxAgeSeconds optional

---

project/pom.xml

Notably this fixes an issue with duplicate module-version files in
JAXB.  Release notes:
https://github.com/basepom/duplicate-finder-maven-plugin/releases

Upgrade to duplicate-finder-maven-plugin 1.5.0

---

core/pom.xml
project/pom.xml

Java 9 modularization removed these.

Add missing javax dependencies for modern Java

---

blobstore/src/main/java/org/jclouds/blobstore/TransientStorageStrategy.java
blobstore/src/test/java/org/jclouds/blobstore/integration/TransientBlobIntegrationTest.java

JCLOUDS-1582: fixes a bug in the transient blobstore where after
uploading a multipart upload, GET/HEAD returns the hash of the content,
rather than the MPU ETag.

Store the MPU ETag for the transient blobstore

---

providers/azureblob/pom.xml
providers/azureblob/src/main/java/org/jclouds/azure/storage/config/AuthType.java
providers/azureblob/src/main/java/org/jclouds/azure/storage/config/AzureStorageOAuthConfigFactory.java
providers/azureblob/src/main/java/org/jclouds/azure/storage/config/AzureStorageProperties.java
providers/azureblob/src/main/java/org/jclouds/azure/storage/filters/SharedKeyLiteAuthentication.java
providers/azureblob/src/main/java/org/jclouds/azure/storage/util/storageurl/StorageAccountInVhost.java
providers/azureblob/src/main/java/org/jclouds/azureblob/AzureBlobApiMetadata.java
providers/azureblob/src/main/java/org/jclouds/azureblob/AzureBlobProviderMetadata.java
providers/azureblob/src/main/java/org/jclouds/azureblob/binders/BindAzureBlobMetadataToRequest.java
providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/AzureBlobRequestSigner.java
providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/config/AzureBlobStoreContextModule.java
providers/azureblob/src/main/java/org/jclouds/azureblob/config/AzureBlobHttpApiModule.java
providers/azureblob/src/main/java/org/jclouds/azureblob/config/AzureBlobModule.java
providers/azureblob/src/test/java/org/jclouds/azure/storage/util/storageurl/StorageAccountInVhostTest.java
providers/azureblob/src/test/java/org/jclouds/azureblob/AzureBlobClientAdTest.java
providers/azureblob/src/test/java/org/jclouds/azureblob/AzureBlobClientLiveTest.java

JCLOUDS-1558: Implements the Azure AD authentication for Azure Blob,
using the OAuth module. Added more parameters to the AzureBlob provider:
- azureblob.auth
- azureblob.account
- azureblob.tenantId
The "auth" parameter is used to specify whether Key/SAS auth or Active
Directory is used. When using Active Directory auth, the identity no
longer maps to the storage account, which has to be specified
explicitly. The tenant ID also needs to be supplied to construct the
auth URL to obtain the token correctly.

JCLOUDS-1558: AzureBlob: Active Directory Auth

---

providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/domain/Deployment.java
providers/azurecompute-arm/src/main/java/org/jclouds/azurecompute/arm/domain/Value.java

JCLOUDS-1584 : Deployment API fails when ARM Template deploys for creating Virtual Machine.

JCLOUDS-1584 : Deployment API fails when ARM Template deploys 

---

project/pom.xml

Guice 4.2.3 makes illegal reflective accesses that Java 17 does not
allow.  References google/guice#1133.  Release notes:
https://github.com/google/guice/wiki/Guice501

JCLOUDS-1586: Upgrade to Guice 5.0.1

---

project/pom.xml

Snyk identifies now previos version of gson as vulnerable. This updates gson to the fixed version
skyn report: https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLECODEGSON-1730327
gson PR: https://github.com/google/gson/pull/1991

Bump google gson to 2.8.9 due to detected vulnerability

---

apis/atmos/pom.xml
apis/cloudwatch/pom.xml
apis/s3/pom.xml
apis/sts/pom.xml
drivers/log4j/pom.xml
drivers/log4j/src/main/java/org/jclouds/logging/log4j/Log4JLogger.java
loadbalancer/pom.xml
project/pom.xml
providers/b2/pom.xml
skeletons/standalone-compute/pom.xml

This addresses a critical CVE:
https://logging.apache.org/log4j/2.x/security.html

JCLOUDS-1589: Upgrade to log4j 2.16.0

---

apis/s3/src/main/java/org/jclouds/s3/S3ApiMetadata.java
apis/s3/src/main/java/org/jclouds/s3/config/S3HttpApiModule.java
apis/s3/src/main/java/org/jclouds/s3/reference/S3Constants.java
providers/aws-s3/src/main/java/org/jclouds/aws/s3/AWSS3ApiMetadata.java
providers/aws-s3/src/main/java/org/jclouds/aws/s3/config/AWSS3HttpApiModule.java
providers/aws-s3/src/test/java/org/jclouds/aws/s3/AWSS3ClientTest.java
providers/aws-s3/src/test/java/org/jclouds/aws/s3/blobstore/AWSS3BlobSignerV4ExpectTest.java
providers/aws-s3/src/test/java/org/jclouds/aws/s3/internal/BaseAWSS3ClientExpectTest.java

Previously s3 always used v2 and aws-s3 always used v4.  Now s3
defaults to v2 and can override to v4.  Note that this does not change
BlobRequestSigner.

JCLOUDS-1594: Allow overriding S3 signer

---

apis/glacier/src/test/java/org/jclouds/glacier/GlacierClientLiveTest.java
apis/glacier/src/test/java/org/jclouds/glacier/GlacierClientMockTest.java
project/pom.xml

Enabled by requiring Java 8.  Also fix some minor API breakage.

Upgrade to assertj 3.23.1

---

project/pom.xml
providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/handlers/GoogleCloudStorageClientErrorRetryHandler.java

Upgrade to jax-rs 2.1.1

---

blobstore/src/main/java/org/jclouds/blobstore/TransientStorageStrategy.java

`ByteSourcePayload.openStream` is not thread safe and lack of
synchronization can throw `ArrayIndexOutOfBoundsException`s.  Instead
deep copy the underlying `Payload`.  Fixes gaul/s3proxy#303.

Deep copy Blob in LocalBlobStore.getBlob

---

core/src/main/java/org/jclouds/Constants.java
core/src/main/java/org/jclouds/proxy/internal/GuiceProxyConfig.java
drivers/okhttp/src/main/java/org/jclouds/http/okhttp/DelegatingSocketFactory.java
drivers/okhttp/src/main/java/org/jclouds/http/okhttp/OkHttpCommandExecutorService.java

Added support for  proxy server type = HTTPS

JCLOUDS-1617: Fix HTTPS support in OkHttpCommandExecutorService

---

apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java

This reduces the number of stat calls required when prefix is deep in the filesystem hierarchy.  Further optimizations to delimiter are possible. References gaul/s3proxy#473.

JCLOUDS-1371: JCLOUDS-1488: optimize fs prefix

---

apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java
apis/filesystem/src/test/java/org/jclouds/filesystem/FilesystemBlobStoreTest.java
apis/filesystem/src/test/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImplTest.java
blobstore/src/main/java/org/jclouds/blobstore/LocalStorageStrategy.java
blobstore/src/main/java/org/jclouds/blobstore/TransientStorageStrategy.java
blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java

`populateBlobKeysInContainer` will no longer recurse when the delimiter matches "/".  This makes listing deep hierarchies with a delimiter faster.  Note that the general `LocalBlobStore` handling is still required for the general cases.  This requires removing a bogus test case.  References gaul/s3proxy#473.

JCLOUDS-1371: Optimize filesystem delimiter

---

apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java

Fixes gaul/s3proxy#490.  This fixes a regression from 41ce90ec360a46cb7b03f7cb8b66e01a113aa5b6.  Continue to support Windows logic although it is unclear if this is necessary.

Atomically replace objects in filesystem putBlob

---

blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java

This removes a previous workaround for opening too many `FileInputStream` and exhausting rlimits.

Lazily open parts during `LocalBlobStore` complete MPU

---

.asf.yaml
.github/workflows/ci.yaml

TravisCI is not allowed anymore for ASF projects. This PR moves our CI/PR build to GHA.

Replace TravisCI with GitHub Actions

---

core/src/main/java/org/jclouds/json/config/GsonModule.java
core/src/main/java/org/jclouds/reflect/Reflection2.java
core/src/test/java/org/jclouds/json/JsonTest.java
core/src/test/java/org/jclouds/lifecycle/config/LifeCycleModuleTest.java
core/src/test/java/org/jclouds/rest/binders/BindToJsonPayloadTest.java
scriptbuilder/src/test/java/org/jclouds/scriptbuilder/statements/login/AdminAccessBuilderSpecTest.java

* Remove `Reflection` access modification
* Make some fields `public` so reflection can access them with strong encapsulation
* Ignore test which fails due to differences in `File` serialization

Java 9/16 strong encapsulation fixes

---

core/src/test/java/org/jclouds/rest/binders/BindToJsonPayloadTest.java

Using gson on a File directly breaks Java strong encapsulation.

Use a class with a File member

---

project/pom.xml

This blocks upgrading gson.  References #176.

Remove bnd

---

core/src/main/java/org/jclouds/json/config/GsonModule.java
core/src/main/java/org/jclouds/json/internal/DeserializationConstructorAndReflectiveTypeAdapterFactory.java
core/src/test/java/org/jclouds/json/internal/DeserializationConstructorAndReflectiveTypeAdapterFactoryTest.java
project/pom.xml

~~This also upgrades bnd to 7.0.0-SNAPSHOT to work around a `META-INF/versions/9/module-info.class=module-info` issue.  Obviously we cannot merge this due to the use of a SNAPSHOT version but maybe someone has a better suggestion how to approach this?~~
Removed bnd in #177.

JCLOUDS-1618: Upgrade to gson 2.10.1

---

apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java

I found that getBlobAccess checks file exists, but getContainerAccess doesn't check. This causes s3proxy throws exceptions when OPTIONS a non-exist bucket. https://github.com/gaul/s3proxy/pull/561

check file exists in getContainerAccess

---

core/src/main/java/org/jclouds/http/HttpUtils.java
providers/azureblob/src/main/java/org/jclouds/azure/storage/config/AuthType.java
providers/azureblob/src/main/java/org/jclouds/azure/storage/filters/SharedKeyLiteAuthentication.java

This is the recommended signature scheme for Azure, and the only scheme that is supported by the Azurite emulator.
https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key

implement support for SharedKey signature

---

blobstore/src/main/java/org/jclouds/blobstore/config/LocalBlobStore.java
blobstore/src/test/java/org/jclouds/blobstore/strategy/internal/ListContainerTest.java

If the metadata ends with delimiter, it is removed in `DelimterFilter.apply`, then add it back by loop `commonPrefixes`. But many information in the metadata lost, such as lastModified time. My solution is keeping them in the DelimeterFilter.

do not remove md in DelimeterFilter then add it by commonPrefixes; just keep it

---

providers/b2/src/main/java/org/jclouds/b2/filters/RequestAuthorization.java
providers/b2/src/test/java/org/jclouds/b2/features/B2TestUtils.java
providers/b2/src/test/resources/create_bucket_request.json
providers/b2/src/test/resources/delete_bucket_request.json
providers/b2/src/test/resources/list_buckets_request.json
providers/b2/src/test/resources/update_bucket_request.json

Fixes the authorization error with b2 application keys.
Tested with s3proxy and curl
https://issues.apache.org/jira/projects/JCLOUDS/issues/JCLOUDS-1519
https://github.com/gaul/s3proxy/issues/298

fixes bug #1519

---

core/src/main/java/org/jclouds/http/UriTemplates.java
core/src/test/java/org/jclouds/http/UriTemplatesTest.java

https://issues.apache.org/jira/projects/JCLOUDS/issues/JCLOUDS-1630

JCLOUDS-1630: Handle URI template properly with opened curve bracket

---

apis/s3/src/test/java/org/jclouds/s3/filters/RequestAuthorizeSignatureV4Test.java
providers/aws-s3/src/main/java/org/jclouds/aws/s3/filters/AWSRequestAuthorizeSignatureV4.java
providers/aws-s3/src/test/java/org/jclouds/aws/s3/filter/AwsRequestAuthorizeSignatureV4Test.java

https://issues.apache.org/jira/projects/JCLOUDS/issues/JCLOUDS-1631

JCLOUDS-1631: fix AWSRequestAuthorizeSignatureV4 when query contains special chars

---

apis/s3/src/main/java/org/jclouds/s3/domain/ObjectMetadata.java
blobstore/src/main/java/org/jclouds/blobstore/domain/Tier.java
providers/azureblob/src/main/java/org/jclouds/azureblob/domain/AccessTier.java
providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/domain/DomainResourceReferences.java

The former replaces INFREQUENT.  References gaul/s3proxy#625.

JCLOUDS-1635: Add COOL and COLD to Tier

---

apis/s3/src/main/java/org/jclouds/s3/filters/AwsHostNameUtils.java
apis/s3/src/test/java/org/jclouds/s3/filters/AwsHostNameUtilsTest.java

Virtual private clouds are a relatively new feature of AWS. The jclouds AWS endpoint regex was not originally designed to be able to handle VPC formatted endpoints. This new expanded regex does the trick. The change also (incidentally) allows the regex to recognize both forms of basic s3 endpoints: s3-region and s3.region.

Modify S3 endpoint regex pattern to support VPC endpoints.

---

providers/azureblob/src/main/java/org/jclouds/azureblob/blobstore/AzureBlobStore.java
providers/azureblob/src/test/java/org/jclouds/azureblob/blobstore/AzureBlobStoreTest.java

Despite [JCLOUDS-1615](https://issues.apache.org/jira/browse/JCLOUDS-1615), using base64url encoded values is not supported by the [Put Block](https://learn.microsoft.com/en-us/rest/api/storageservices/put-block) endpoint.
When attempting to query this endpoint with `partNumber` set to `248` (which is `blockid: AAAA-A==`) I received this error:
```xml
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:632a8422-501e-006c-3db4-e238fb000000
Time:2024-07-30T19:10:34.4638223Z</Message><QueryParameterName>blockid</QueryParameterName><QueryParameterValue>AAAA-A==</QueryParameterValue><Reason>Not a valid base64 string.</Reason></Error>
```
I have confirmed directly …

Fixes issue with AzureBlobStore blockid incorrectly using base64url encoding

---

core/src/main/java/org/jclouds/ContextBuilder.java

Azure cloud providers specifically use an identity as part of their endpoint. 
When attempting to use a ContextBuilder with the (new-ish?) credentialsSupplier option, we were seeing errors building an endpoint due to string interpolation failures, since the Azure module was not expecting a Supplier<Credentials> (rather, a specific `identity` and `credential`)
This is not a comprehensive fix (any subsequent change to the identity will not be reflected in the endpoint going forward) but partially addresses a serious problem (unable to use ContextBuilder's `credentialsSupplier` for Azure providers)
I plan on a more thorough change that will allow on-the-fly changes to an Azure provider's identity/credential, but this is more difficult. I believe I'll need to find every place where the …

Fix ContextBuilder bug when using credentials supplier with azureblob

---

apis/ec2/src/main/java/org/jclouds/ec2/compute/loaders/LoadAllocationIdForInstanceOrNull.java
apis/ec2/src/main/java/org/jclouds/ec2/domain/PublicIpInstanceIdPair.java
apis/ec2/src/main/java/org/jclouds/ec2/features/ElasticIPAddressApi.java
apis/ec2/src/main/java/org/jclouds/ec2/xml/DescribeAddressesResponseHandler.java
apis/ec2/src/test/java/org/jclouds/ec2/compute/loaders/LoadPublicIpForInstanceOrNullTest.java
apis/ec2/src/test/java/org/jclouds/ec2/xml/DescribeAddressesResponseHandlerTest.java
providers/aws-ec2/src/main/java/org/jclouds/aws/ec2/features/RouteTableApi.java
providers/aws-ec2/src/test/java/org/jclouds/aws/ec2/features/RouteTableApiLiveTest.java

RouteTable describe now has an ability to describe by filter which allows for searching by 'vpc-id' for instance.
PublicIpInstanceIpPair for EC2 how has the AllocationId associated with that IP pair along with the ability to describe and release IP Address by its associated AllocationId in EC2

Enhancement to RouteTable describe and adding AllocationId as attribute to PublicIpInstanceIdPair and related describes

---

core/src/main/java/org/jclouds/http/internal/JavaUrlHttpCommandExecutorService.java
providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/config/GoogleCloudStorageOAuthScopes.java
providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/features/BucketAccessControlsApi.java
providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/features/BucketApi.java
providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/features/DefaultObjectAccessControlsApi.java
providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/features/ObjectAccessControlsApi.java
providers/google-cloud-storage/src/main/java/org/jclouds/googlecloudstorage/features/ObjectApi.java
providers/google-cloud-storage/src/test/java/org/jclouds/googlecloudstorage/features/BucketAccessControlsApiExpectTest.java
providers/google-cloud-storage/src/test/java/org/jclouds/googlecloudstorage/features/BucketApiExpectTest.java
providers/google-cloud-storage/src/test/java/org/jclouds/googlecloudstorage/features/DefaultObjectAccessControlsApiExpectTest.java
providers/google-cloud-storage/src/test/java/org/jclouds/googlecloudstorage/features/ObjectAccessControlsApiExpectTest.java
providers/google-cloud-storage/src/test/java/org/jclouds/googlecloudstorage/features/ObjectApiMockTest.java

Modern Java versions do not allow the reflection workaround previously used.

JCLOUDS-1641: Use POST instead of PATCH for GCS

---

apis/s3/src/main/java/org/jclouds/s3/S3Client.java
apis/s3/src/main/java/org/jclouds/s3/binders/BindOwnershipControlsToXMLPayload.java
apis/s3/src/main/java/org/jclouds/s3/binders/BindPublicAccessBlockConfigurationToXMLPayload.java
apis/s3/src/main/java/org/jclouds/s3/domain/PublicAccessBlockConfiguration.java
apis/s3/src/test/java/org/jclouds/s3/S3ClientLiveTest.java
apis/s3/src/test/java/org/jclouds/s3/services/BucketsLiveTest.java
blobstore/src/test/java/org/jclouds/blobstore/integration/internal/BaseBlobIntegrationTest.java
providers/aws-s3/src/main/java/org/jclouds/aws/s3/blobstore/AWSS3BlobStore.java
providers/aws-s3/src/test/java/org/jclouds/aws/s3/AWSS3ClientLiveTest.java
providers/aws-s3/src/test/java/org/jclouds/aws/s3/blobstore/integration/AWSS3BlobIntegrationLiveTest.java
providers/aws-s3/src/test/java/org/jclouds/aws/s3/services/AWSBucketsLiveTest.java

AWS changed the defaults when creating buckets to prevent public-read and other canned ACLs.  Background:
https://stackoverflow.com/a/76102067/2800111

JCLOUDS-1644: Create AWS S3 buckets with ownership and public access block

---

providers/digitalocean2/src/main/java/org/jclouds/digitalocean2/compute/config/DigitalOcean2ComputeServiceContextModule.java
providers/digitalocean2/src/main/java/org/jclouds/digitalocean2/compute/extensions/DigitalOcean2ImageExtension.java
providers/digitalocean2/src/main/java/org/jclouds/digitalocean2/domain/Action.java
providers/digitalocean2/src/main/java/org/jclouds/digitalocean2/domain/DropletCreate.java
providers/digitalocean2/src/main/java/org/jclouds/digitalocean2/features/ActionApi.java
providers/digitalocean2/src/test/java/org/jclouds/digitalocean2/compute/config/ActionDonePredicateTest.java
providers/digitalocean2/src/test/java/org/jclouds/digitalocean2/internal/BaseDigitalOcean2ApiLiveTest.java
providers/digitalocean2/src/test/resources/droplet-create-res.json

Changed org.jclouds.digitalocean2.domain.Action.id from int to long
in order to fit large numbers sent in responses.
This appears to be a misinterpretation of DigitalOceans ApiDocs,
because in these docs, they fail to specify the size of their
"integer" type. Therefore, I looked into their official GO Api
sources at https://github.com/digitalocean/godo. There, they use
the int type, which is platform dependant and usually has 64 bits.
Therefore our digitalocean2 provider, should be refactored, changing
**_all_** Ids from int/Integer to long/Long.
This PR is just the immediate fixup to make the jclouds (jenkins plugin)
work with current DigitalOcean again. The refactoring should be done
ASAP, otherwise we could run into similar problems, when the id values in
their API-resonses grow over …

Fix digitalocean2 NumberFormatException

---

apis/s3/src/main/java/org/jclouds/s3/handlers/S3RedirectionRetryHandler.java

Under some conditions, attempting to parse an AWSError from a request (org.jclouds.aws.util.AWSUtils#parseAWSErrorFromContent) can wind up with a null result. 
S3RedirectionRetryHandler was not handling such null responses gracefully, and was instead hitting a NullPointerException. 
This one-line fix changes S3RedirectionRetryHandler to null-check results from the method mentioned above.

Fix NPE on failure to parse AWSError when determing whether to retry request
